### ISSUE TITLE
Execution error (ClassNotFoundException) 

### ISSUE THREAD

**Issue by Nek** [pfeodrippe/vybe#2]
Hello. I'm sorry for just dumping the error here; I don't have that much knowledge of Java runtime to properly debug it.

Running:

`clj -M:dev -m vybe.native.loader && clj -M:osx -m vybe.raylib`

Gives me:
```
Execution error (ClassNotFoundException) at java.net.URLClassLoader/findClass (URLClassLoader.java:445).
org.vybe.raylib.raylib

Full report at:
/var/folders/1_/71ly9lqn40152x_03prnmt_00000gn/T/clojure-6552735894732859395.edn
```

[clojure-6552735894732859395.edn](https://gist.github.com/Nek/4d01690f51adf50ea96992f9486a72b5)

**Comment by pfeodrippe** [comment]
Hi @Nek, thanks for the report.

Which device are you trying to run it on, a Mac (arm)?

**Comment by Nek** [comment]
```
Apple M1 Max
Sonoma 14.4.1
```

**Comment by pfeodrippe** [comment]
The error is caused by not having the dynamic libs properly loaded, are you able to run https://github.com/pfeodrippe/vybe-games? It will download the jar from clojars with the dynamic libs already (at least for arm macs)

**Comment by pfeodrippe** [comment]
> Apple M1 Max
> Sonoma 14.4.1

Nice, hopefully you don’t need to run the jextract shell script then, but if you run it, did it work?

**Comment by Nek** [comment]
> The error is caused by not having the dynamic libs properly loaded, are you able to run https://github.com/pfeodrippe/vybe-games? It will download the jar from clojars with the dynamic libs already (at least for arm macs)

Thank you, @pfeodrippe! It works.
![CleanShot 2024-06-26 at 00 06 05](https://github.com/pfeodrippe/vybe/assets/132011/fc3ded53-a5a4-444c-bd61-4bf007c23f88)

**Comment by Nek** [comment]
> > Apple M1 Max
> > Sonoma 14.4.1
> 
> Nice, hopefully you don’t need to run the jextract shell script then, but if you run it, did it work?

I had to install zig, download jextract, and put it in the appropriate location. But then it just worked.

**Comment by pfeodrippe** [comment]
> > The error is caused by not having the dynamic libs properly loaded, are you able to run https://github.com/pfeodrippe/vybe-games? It will download the jar from clojars with the dynamic libs already (at least for arm macs)
> 
> Thank you, @pfeodrippe! It works. ![CleanShot 2024-06-26 at 00 06 05](https://private-user-images.githubusercontent.com/132011/342947817-fc3ded53-a5a4-444c-bd61-4bf007c23f88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzNTQzMDgsIm5iZiI6MTcxOTM1NDAwOCwicGF0aCI6Ii8xMzIwMTEvMzQyOTQ3ODE3LWZjM2RlZDUzLWE1YTQtNDQ0Yy1iZDYxLTRiZjAwN2MyM2Y4OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNVQyMjIwMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOGZhZTlmNTJjZmM4ZmRmNWVjZGRhMzQ1NDdlZTEzMDBiMTE2ZTM3ZWE1Y2EyNDNhNzNiZWE1MDEyMWRkNzBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iLgtjU61veK_ELifgXRS8AjpdpFiik2DqyKxvyfri5c)

Hunnn, and this is all you see? It should load the 3D environment after this. Let me know if you see some errors in the log or in the REPL o/

**Comment by Nek** [comment]
No errors. Just this screen with a MacOS spinner.
This is what I get in Terminal:
```
nek@Nek ~/G/vybe-games (main) [SIGTERM]> clj -M:dev -m vybe.native.loader && clj -M:osx -m vybe.raylib

:nrepl-connection :port 7888
INFO: Initializing raylib 5.1-dev
INFO: Platform backend: DESKTOP (GLFW)
INFO: Supported raylib modules:
INFO:     > rcore:..... loaded (mandatory)
INFO:     > rlgl:...... loaded (mandatory)
INFO:     > rshapes:... loaded (optional)
INFO:     > rtextures:. loaded (optional)
INFO:     > rtext:..... loaded (optional)
INFO:     > rmodels:... loaded (optional)
INFO:     > raudio:.... loaded (optional)
INFO: DISPLAY: Trying to enable MSAA x4
INFO: wantWindowed: 0, size: 600x600
INFO: DISPLAY: Device initialized successfully
INFO:     > Display size: 1728 x 1117
INFO:     > Screen size:  600 x 600
INFO:     > Render size:  600 x 600
INFO:     > Viewport offsets: 0, 0
INFO: GLAD: OpenGL extensions loaded successfully
INFO: GL: Supported extensions count: 43
INFO: GL: OpenGL device information:
INFO:     > Vendor:   Apple
INFO:     > Renderer: Apple M1 Max
INFO:     > Version:  4.1 Metal - 88
INFO:     > GLSL:     4.10
INFO: GL: VAO extension detected, VAO functions loaded successfully
INFO: GL: NPOT textures extension detected, full NPOT textures supported
INFO: GL: DXT compressed textures supported
INFO: GLFW platform: Cocoa
INFO: PLATFORM: DESKTOP (GLFW): Initialized successfully
INFO: TEXTURE: [ID 1] Texture loaded successfully (1x1 | R8G8B8A8 | 1 mipmaps)
INFO: TEXTURE: [ID 1] Default texture loaded successfully
INFO: SHADER: [ID 1] Vertex shader compiled successfully
INFO: SHADER: [ID 2] Fragment shader compiled successfully
INFO: SHADER: [ID 3] Program shader loaded successfully
INFO: SHADER: [ID 3] Default shader loaded successfully
INFO: RLGL: Render batch vertex buffers loaded successfully in RAM (CPU)
INFO: RLGL: Render batch vertex buffers loaded successfully in VRAM (GPU)
INFO: RLGL: Default OpenGL state initialized successfully
INFO: TEXTURE: [ID 2] Texture loaded successfully (128x128 | GRAY_ALPHA | 1 mipmaps)
INFO: FONT: Default font loaded successfully (224 glyphs)
INFO: TIMER: Target time per frame: 16.667 milliseconds
INFO: TIMER: Target time per frame: 16.667 milliseconds
INFO: FILEIO: [/Users/nek/GitHub/vybe-games/resources/models.glb] File loaded successfully
INFO: MODEL: [/Users/nek/GitHub/vybe-games/resources/models.glb] Model basic data (glb) loaded successfully
INFO:     > Meshes count: 4
INFO:     > Materials count: 3 (+1 default)
INFO: VAO: [ID 2] Mesh uploaded successfully to VRAM (GPU)
INFO: VAO: [ID 3] Mesh uploaded successfully to VRAM (GPU)
INFO: VAO: [ID 4] Mesh uploaded successfully to VRAM (GPU)
INFO: VAO: [ID 5] Mesh uploaded successfully to VRAM (GPU)

```

**Comment by pfeodrippe** [comment]
>No errors. Just this screen with a MacOS spinner.
This is what I get in Terminal:

I've opened my wife's computer, download the vybe-games repo, run

```
clj -M:dev -m vybe.native.loader && clj -M:osx -m vybe.raylib
```

,started the REPL and then evaluated `init` in `leo.clj`. 

Things are working fine in the new computer, if could record your screen (I recommend OBS if you don't have a preferred way of doing it) when doing the manual steps, please, it would help \o

**Comment by pfeodrippe** [comment]
I will also put these in a script so you don't even need to connect to the REPL to make the game window appear \o

**Comment by pfeodrippe** [comment]
If you prefer to google meet, I'm also available \o

**Comment by Nek** [comment]
Google Meet is only available for company accounts in Sweden. Telegram has screen sharing; ping me (nikita_dudnik) if you are there. Otherwise, we can always use Zoom. 😑

**Comment by Nek** [comment]
Ah! There is also <https://meet.jit.si/>. Anyway, I'm up for it. 😄

**Comment by pfeodrippe** [comment]
So things are working for you now with the latest version of vybe and https://github.com/pfeodrippe/vybe-games =D Thanks for the report
